development:
  adapter: postgresql
  encoding: unicode
  database: scraper_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: scraper_test
  pool: 5
  username: postgres
  password: postgres